# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='representation_name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='unique representation name'),
        ),
    ]
