# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='post title')),
                ('content', models.TextField(max_length=30000, verbose_name='post content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='post created')),
                ('last_edited', models.DateTimeField(auto_now=True, verbose_name='post edited')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'general post',
                'verbose_name_plural': 'general posts',
            },
        ),
    ]
